version: '3.7'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: L0c4l_P4ssW0rd
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
      PGDATA: /var/lib/postgresql/data/db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  test-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: L0c4l_P4ssW0rd
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
      PGDATA: /var/lib/postgresql/data/db
    ports:
      - "5433:5432"
    volumes:
      - testdb:/var/lib/postgresql/data

  eass:
    image: eass_moodle:4.1
    depends_on:
      - db
      - test-db
    environment:
      - HOST_TYPE
      - IDE_KEY=eass-docker
      - SITE_DOMAIN=eass
      - LISTENING_PORT=80
    ports:
      - "80:80"
    volumes:
      - ../siteroot:/siteroot
    entrypoint: /entrypoint.sh

  exttests:
    image: moodlehq/moodle-exttests

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

volumes:
  db:
  testdb:

networks:
  default:
    name: local-eass-net