version: '3.5'

services:
  db39:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: L0c4l_P4ssW0rd
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
      PGDATA: /var/lib/postgresql/data/db39
    ports:
      - "5432:5432"
    volumes:
      - db39:/var/lib/postgresql/data

  test-db39:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: L0c4l_P4ssW0rd
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
      PGDATA: /var/lib/postgresql/data/db39
    ports:
      - "5433:5432"
    volumes:
      - testdb39:/var/lib/postgresql/data

  eass39:
    image: eass_moodle:3.9
    depends_on:
      - db39
      - test-db39
    environment:
      - HOST_TYPE
      - IDE_KEY=eass-docker
      - SITE_DOMAIN=eass39
      - LISTENING_PORT=80
    ports:
      - "80:80"
    volumes:
      - ../siteroot:/siteroot
    entrypoint: /entrypoint.sh

  exttests:
    image: moodlehq/moodle-exttests

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

volumes:
  db39:
  testdb39:

networks:
  default:
    name: local-eass39-net